# Generated by Django 4.2 on 2023-05-05 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_alter_task_done"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="user",
            new_name="created_by",
        ),
    ]
